# Generated by Django 6.0.3 on 2026-04-16 17:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('upload', 'File Upload'), ('predict', 'Prediction Made'), ('download', 'Downloaded Results'), ('login', 'Login'), ('logout', 'Logout'), ('view_dashboard', 'Viewed Dashboard'), ('filter_data', 'Filtered Data')], max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
